source "https://rubygems.org"

gem "rake", "~> 10.1.1"

gem "puppet-lint", "0.4.0.pre1"

gem "puppet", "~> 3.6.0"

gem "parallel_tests", "0.9.2"
gem "parallel" , "0.6.1"

gem "rspec", "< 3.0.0"

gem "rspec-puppet", :git => 'https://github.com/rodjek/rspec-puppet.git',
    :ref => '03e94422fb'

gem "ruby-progressbar", "~> 1.4.1"

gem "highline", "~> 1.6.21"

gem "hiera", "1.1.2"
gem "hiera-puppet", "1.0.0"

gem "hiera-eyaml", "~> 2.0.0"

gem "rubocop", "~> 0.21.0"

gem "puppet-syntax"