http:
  port: <%= @capd_send_mail_port %>
  adminPort: <%= @capd_send_mail_admin_port %>

smtpHost: <%= @capmanagement_hostname %>
smtpPort: 25

healthCheckEmailAddress: <%= @capd_send_mail_health_check_email_address %>

logging:

  console:
     enabled: true

     # Do not display log statements below this threshold to stdout.
     threshold: ALL

     logFormat: '%date{ISO8601} level=[%level] logger=[%logger] thread=[%thread] message=[%message] %replace(exception=[%xException]){''^exception=\[\]$'',''''}%n%nopex'

