# This class defines which users have production access
class users::groups::production_access {
  include users::garethw
  include users::trevorr
  include users::piotrgo
  include users::roryh
  include users::robl
  include users::krzysztofo
  include users::krzysztofr
  include users::wojciechh
  include users::michaelv
  include users::peterso
  include users::kylet
  include users::simonw
  include users::mario
  include users::lisasmy
  include users::pawelk
  include users::pacheson
  include users::awright
  include users::chrisk
  include users::owenc
  include users::jonf
  include users::tomaszj
  include users::jayeshs
  include users::tomaszp
  include users::chijiokea
  include users::ireneuszp
  include users::stevena
  include users::javierlar
  include users::willh
  include users::jayf
  include users::apawargi
  include users::sriroopag
  include users::cormacq
  include users::dspence
  include users::hannahm
  include users::andrewg
  include users::aperez
  include users::mjamiolkowski
  include users::davidc
  include users::slawomirm
  include users::dmcaleenan
  include users::jeffreyw
  include users::sylwester
  include users::maciejciszewski2
  include users::tomaszj
  include users::tomaszs
  include users::leeg
  include users::tommaso
  include users::pawell
  include users::rafalk
  include users::xaviers
  include users::alanj
}
